"""Bit-exact golden-fixture regression for the single-portfolio engine.

Every scenario in tests/golden_scenarios.py is re-run and compared against
pre-captured .npz / .meta.json fixtures.  Any numeric drift — from an engine
change, a numpy upgrade, or anything else — fails this test.

Fixtures are generated by scripts/capture_golden_fixtures.py and committed
to the repo.  This test NEVER writes fixtures.
"""

import json
import os
import sys

import numpy as np
import pytest

from engine.simulation import run_simulation

# Ensure tests/ is on sys.path so we can import golden_scenarios (no test_
# prefix, so pytest won't collect it as a test module).
_tests_dir = os.path.dirname(__file__)
if _tests_dir not in sys.path:
    sys.path.insert(0, _tests_dir)

import golden_scenarios  # noqa: E402 (must come after sys.path insert)

_FIXTURE_DIR = os.path.join(_tests_dir, "fixtures", "golden")


@pytest.mark.parametrize("name", sorted(golden_scenarios.SCENARIOS.keys()))
def test_golden_single_mode(name: str) -> None:
    npz_path = os.path.join(_FIXTURE_DIR, f"{name}.npz")
    meta_path = os.path.join(_FIXTURE_DIR, f"{name}.meta.json")

    # Fail (not skip) if fixtures are missing.
    if not os.path.isfile(npz_path) or not os.path.isfile(meta_path):
        raise AssertionError(
            "golden fixtures missing — run scripts/capture_golden_fixtures.py"
        )

    # Load stored fixtures.
    data = np.load(npz_path)
    with open(meta_path, "r") as f:
        meta = json.load(f)

    # Re-run the scenario.
    params, guardrails = golden_scenarios.SCENARIOS[name]()
    result = run_simulation(params, guardrails=guardrails)

    # Compare every stored array bit-exactly.
    arrays = [
        "bal_over_time",
        "prop_over_time",
        "final_portfolio",
        "final_property",
        "estate_final",
        "ruined",
    ]
    # Funded-ratio guardrail scenarios also have multiplier percentiles,
    # nested under result["guardrail_mult_percentiles"] as p10/p50/p90.
    fresh = dict(result)
    if "mult_p10" in data:
        gp = result["guardrail_mult_percentiles"]
        fresh.update({"mult_p10": gp["p10"], "mult_p50": gp["p50"],
                      "mult_p90": gp["p90"]})
        arrays.extend(["mult_p10", "mult_p50", "mult_p90"])

    stored_np_version = meta.get("numpy_version")
    running_np_version = np.__version__

    for key in arrays:
        try:
            np.testing.assert_array_equal(data[key], fresh[key])
        except AssertionError as exc:
            if stored_np_version != running_np_version:
                msg = (
                    f"{exc.args[0]}\n"
                    f"(stored numpy_version={stored_np_version!r}, "
                    f"running np.__version__={running_np_version!r})"
                )
                raise AssertionError(msg) from exc
            raise

    # Compare JSON scalars with exact ==.
    for key in ("summary", "mean_withdraw_rate", "max_withdraw_rate",
                "mean_withdraw_value"):
        stored = meta[key]
        computed = result[key].tolist() if hasattr(result[key], "tolist") else result[key]
        try:
            assert stored == computed, (
                f"{key} mismatch:\n  stored   = {stored!r}\n  computed = {computed!r}"
            )
        except AssertionError as exc:
            if stored_np_version != running_np_version:
                msg = (
                    f"{exc.args[0]}\n"
                    f"(stored numpy_version={stored_np_version!r}, "
                    f"running np.__version__={running_np_version!r})"
                )
                raise AssertionError(msg) from exc
            raise
